config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :spices, only: [:index, :new, :create]
  end
  resources :spices, only: [:show, :edit, :update, :destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "spices#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/spice.rb
class Spice < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :spices
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/spices_controller.rb
class SpicesController < ApplicationController
  before_action :set_spice, only: %i[ show edit update destroy ]

  # GET /spices or /spices.json
  def index
    @users = User.all
    @spices = Spice.all
  end

  # GET /spices/1 or /spices/1.json
  def show
  end

  # GET /spices/new
  def new
    @spice = User.find(params[:user_id]).spices.new
  end

  # GET /spices/1/edit
  def edit
  end

  # POST /spices or /spices.json
  def create
    @spice = User.find(params[:user_id]).spices.new(spice_params)

    respond_to do |format|
      if @spice.save
        format.html { redirect_to spice_url(@spice), notice: "Spice was successfully created." }
        format.json { render :show, status: :created, location: @spice }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @spice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spices/1 or /spices/1.json
  def update
    respond_to do |format|
      if @spice.update(spice_params)
        format.html { redirect_to spice_url(@spice), notice: "Spice was successfully updated." }
        format.json { render :show, status: :ok, location: @spice }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @spice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spices/1 or /spices/1.json
  def destroy
    @spice.destroy

    respond_to do |format|
      format.html { redirect_to spices_url, notice: "Spice was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_spice
      @spice = Spice.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def spice_params
      params.require(:spice).permit(:name, :quantity, :unit, :ground, :user)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/spices_helper.rb
module SpicesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpiceCurls</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/spices/_form.html.erb
<%= form_with(model: @spice, url: [:user, @spice]) do |form| %>
  <% if spice.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(spice.errors.count, "error") %> prohibited this spice from being saved:</h2>

      <ul>
        <% spice.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.label :unit, style: "display: block" %>
    <%= form.text_field :unit %>
  </div>

  <div>
    <%= form.label :ground, style: "display: block" %>
    <%= form.check_box :ground %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/spices/_spice.html.erb
<div id="<%= dom_id spice %>">
  <p>
    <strong>Name:</strong>
    <%= spice.name %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= spice.quantity %>
  </p>

  <p>
    <strong>Unit:</strong>
    <%= spice.unit %>
  </p>

  <p>
    <strong>Ground:</strong>
    <%= spice.ground %>
  </p>

</div>

app/views/spices/edit.html.erb
<h1>Editing spice</h1>

<%= render "form", spice: @spice %>

<br>

<div>
  <%= link_to "Show this spice", @spice %> |
  <%= link_to "Back to spices", spices_path %>
</div>

app/views/spices/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Spices For Roomie:</h1>

<div id="user-spices">
  <% @users.includes(:spices).each do |user| %>
    <%= render user %>
    <% user.spices.each do |spice| %>
      <%= render spice %>
      <p>
        <%= link_to "Show this spice", spice %>
      </p>
    <% end %>
    <%= link_to "New spice for #{user.name}", new_user_spice_path(user) %>
  <% end %>
</div>

<br>

<section>

<h1>Unclaimed Spices</h1>

<div id="spices">
  <% @spices.each do |spice| %>
    <%= render spice %>
    <p>
      <%= link_to "Show this spice", spice %>
    </p>
  <% end %>
</div>

</section>

app/views/spices/new.html.erb
<h1>New spice for <%= @spice.user.name %></h1>

<%= render "form", spice: @spice %>

<br>

<div>
  <%= link_to "Back to spices", user_spices_path(@spice.user) %>
</div>

app/views/spices/show.html.erb
<p style="color: green"><%= notice %></p>

<% if @spice.user %>
  <h1><%= @spice.user.name %>'s Spice</h1>
<% end %>

<%= render @spice %>

<div>
  <% if @spice.user %>
    <%= link_to "Edit this spice", edit_spice_path(@spice) %> |
    <%= link_to "Back to spices", user_spices_path(@spice.user) %>
  <% end %>

  <%= button_to "Destroy this spice", @spice, method: :delete %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>